- .travis.yml
Also bumps Git LFS to 2.0.2:
- [Git release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.12.2.txt)
- [Git for Windows release notes](https://github.com/git-for-windows/git/releases/tag/v2.12.2.windows.2)
- [Git LFS release notes](https://github.com/git-lfs/git-lfs/releases/tag/v2.0.2)
> Bump Git to 2.12.2

- .travis.yml
- appveyor.yml
- docs/making-changes.md
- script/build-win32.sh
- script/build.sh
- script/package.sh
This adds the same building and packaging steps to AppVeyor, so we can test Windows-specific things easily.
I'd rather leave Travis to be the canonical source for packaging, but I think I can emulate the "package and publish from tag" behaviour from AppVeyor if we need to start building from source.
> AppVeyor support

- script/build-win32.sh
> swap in curl-winssl for curl-openssl on Windows

- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
- script/package.sh
Some other missing bits from #37 
- a consistent approach to computing the SHA256 checksum
- indenting the steps for each build to make them stand out from the rest of the output
- output the file size (friendly, e.g `21M`) after packaging, so you can see at a glance if it looks authentic
> some tracing and cleanup

- .gitignore
- docs/setup.md
- package.json
- script/update-test-harness.js
- test/macos.sh
- test/ubuntu.sh
- test/win32.sh
Fixes #26 by auto-generating the test scripts using on the `.travis.yml` contents. This means you can quickly experiment with build and packaging steps locally:
```
$ ./test/ubuntu.sh
```
Yes, it's a node script. **You don't need to have Node or NPM installed to use these scripts - just for updating**. I wanted to keep this all in bash but the various bash parsing scripts I came across weren't able to map the`matrix.includes` values to keys, so I'm stuck with rolling my own solution and it was quicker to do it with JS.
I'll re-run this script and commit updated versions of the scripts with each release.
> add support for local testing

- .travis.yml
Similar to #43 but applying this to the latest Git release `v2.13.0`
> bump Git LFS to v2.1.1 to address security vulnerability

- script/build-win32.sh
This removes the global `gitattributes` file that ships in MinGit as:
- the behaviour is Windows-specific 
- the `astextplain` script is not bundled in MinGit (it also requires the Perl runtime)
> cleanup gitattributes file from global config

- script/build-ubuntu.sh
Fixes #47 
This brings the binary size from 50MB compressed (131MB uncompressed) to 13MB compressed (27MB uncompressed) by doing two things:
- `make strip install` rather than just `make install` (I'll follow up with macOS and see if that improves it's installer much)
- removing the unnecessary server-side components that ship in the box:
- [`git-shell`](https://git-scm.com/docs/git-shell) - restricted login for SSH access
- `git-receive-pack`, `git-receive-archive` and `git-upload-archive` - related commands that you run within `git-shell`
- [`git-cvsserver`](https://git-scm.com/docs/git-cvsserver) - a CVS server emulator for Git
I figure no-one really wants these tools at this stage, but they're easy to put back in the future if needed.
> Trim linux build size

- .travis.yml
- test/win32.sh
- [Git 2.14.0 release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.14.0.txt)
- [Git for Windows 2.14.0 release notes](https://github.com/git-for-windows/git/releases/tag/v2.14.0.windows.1)
- [Security hotfix around handling SSH URLs](http://marc.info/?l=git&m=150238802328673&w=2)
> update git to 2.14.1

- .travis.yml
- test/macos.sh
- test/ubuntu.sh
- test/win32.sh
Hot off the presses:
- [Git release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.15.0.txt)
- [Git for Windows release notes](https://github.com/git-for-windows/git/releases/tag/v2.15.0.windows.1)
> Update to Git 2.15.0

- .travis.yml
Currently when a tag is pushed to GitHub, Travis kicks off a build and then publishes the artifacts it has without release notes:
This is confusing, and totally unhelpful for downstream consumers.
I _think_ this is how to create the release as a draft first, which a human can then come in and craft the release notes and then :shipit:, based on https://github.com/travis-ci/travis-ci/issues/6132 and https://github.com/bkimminich/juice-shop/commit/727289324b3065bf7825bbb6f4d91b90a6351c32.
> travis should create the draft release first

- .gitignore
- .travis.yml
- script/package.sh
- script/update-test-harness.js
- test/macos.sh
- test/ubuntu.sh
- test/win32.sh
GZIP is relatively ubiquitous in terms of support, but LZMA actually compresses far better in my testing.
```shellsession
Creating archives...
Packages created:
dugite-native--ubuntu-test.tar.gz - 13M - checksum: 14f2f3d572aedd5b4a498b9582ed19ef26a3d3fbeb52251c763a3b08ba865cf7
dugite-native--ubuntu-test.lzma - 5.2M - checksum: 248f581e2eb2460149adb900b59ca82832a5de62597cf2e56173e732d4ce0dfb
```
So I'll start supporting both formats, for a bit of convenience for consumers.
> use LZMA archives which compress far better

- .travis.yml
- appveyor.yml
- test/win32.sh
A minor release due to an upstream segfault discovered when cloning a repository which tracks two paths that differ only in case on a case insensitive filesystem.
- [Git release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.16.1.txt)
- [Git for Windows release notes](https://github.com/git-for-windows/git/releases/tag/v2.16.1.windows.1)
> Update to Git 2.16.1

- .travis.yml
- script/build-arm64-git.sh
- script/build-arm64.sh
- script/build.sh
- script/package.sh
This PR adds an arm64 build for dugite.  
Unfortunately git-lfs doesn't have a prebuilt arm64 binary (see https://github.com/git-lfs/git-lfs/issues/2464 for more details), so the arm64 dugite-native build works as follows:
1. Git is build via a multiarch/debian-debootstrap:arm64-jessie docker container.  This allows cross compilation of arm64 git on a x86 machine.
2. git-lfs is built using the arch flag, eg: `git-lfs/script/bootstrap -arch arm64 -os linux`
> Add arm64 build

- .gitattributes
I tried to build this on windows via bash on windows. But then I got this:
```bash
test/win32.sh: line 2: $'\r': command not found
test/win32.sh: line 7: $'\r': command not found
....(truncated)
```
I manage to solve this by removing all `\r`. So i think `.sh` files have to be enforced to have LF line ending.
> Force .sh files have LF ending

- .travis.yml
- appveyor.yml
- [Git release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.16.2.txt)
- [Git for Windows release notes](https://github.com/git-for-windows/git/releases/tag/v2.16.2.windows.1)
> bump Git and Git for Windows to 2.16.2

- .travis.yml
- appveyor.yml
- [Git LFS release notes](https://github.com/git-lfs/git-lfs/releases/tag/v2.4.0)
> update to Git LFS 2.4.0

- .travis.yml
- appveyor.yml
- [Git release notes](https://github.com/git-for-windows/git/releases/tag/v2.16.3.windows.1)
- [Git for Windows release notes](https://github.com/git-for-windows/git/releases/tag/v2.16.3.windows.1)
> bump Git package to 2.16.3

- .travis.yml
- appveyor.yml
This upgrades Git to 2.17.1 which also addresses CVE 2018-11235.
> bump to latest Git to address security issue

- script/build-win32.sh
See https://github.com/desktop/desktop/issues/4817#issuecomment-393241303
This unset (i.e. removes) the `http.sslCAInfo` default setting from the _system_ level configuration that we ship alongside dugite-native in order for the default behavior of the `schannel` subsystem in curl to be to look inside the Windows certificate store, not in the stock ca bundle.
On GitHub Desktop we want to preserve the behavior of looking in the Windows certificate store because we allow users to add self-signed certificate to that store, see https://github.com/desktop/desktop/pull/2581
> Unset the http.sslCAInfo system-level config variable on Windows

- .travis.yml
- script/build-arm64-git.sh
- script/build-ubuntu.sh
As part of investigation https://github.com/shiftkey/desktop/issues/21 I found myself realising some choices I'd made ages ago were not great:
- the Ubuntu distribution is compiled and linked with `NO_OPENSSL=1` because I wanted to avoid any unnecessary TLS dependencies
- it looks like this means it's compiled and linked with _some other_ TLS dependency
- the vanilla Travis images look like they have multiple `libcurl4-*` dependencies available (and/or installed)
```
$ sudo apt install libcurl4-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libcurl4-dev is a virtual package provided by:
libcurl4-openssl-dev 7.47.0-1ubuntu2.8
libcurl4-nss-dev 7.47.0-1ubuntu2.8
libcurl4-gnutls-dev 7.47.0-1ubuntu2.8
You should explicitly select one …
```
> drop flag and enable linking to OpenSSL again

- .travis.yml
- appveyor.yml
- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
- script/update-test-harness.js
- test/macos.sh
- test/ubuntu.sh
- test/win32.sh
This now means I can bump the version in one spot and should prevent me from overlooking the ARM64 build when upgrading Git LFS
> use single GIT_LFS_VERSION config value rather than multiple URLs

- script/build-win32.sh
Two minor things:
- this config key will change with the next update to Git for Windows (it didn't work previously)
- there are some old `git-credential-*` components in MinGit that are superseded by `git-credential-manager`, no need to also ship them in the box
> tidy up the Windows packaging

- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
This adds some resiliency to the Git LFS packaging process by ensuring the `git-lfs` binary is where we expect it when unpacking:
> check that git-lfs is found where we expect it

- docs/releases.md
- package-lock.json
- package.json
- script/generate-release-notes.js
This PR is a replacement for the manual process that I was previously doing to generate releases.
New release process:
- get yourself a personal access token with `public_repo` scope 
- `git tag {tag name} && git push origin {tag name}`
- wait for the Travis build to complete generating the release artifacts
- `npm run generate-release-notes`
- visit the draft release URL, tweak things, and publish 
✨✨✨ [**Rendered Release Process Notes**](https://github.com/desktop/dugite-native/blob/script-for-updating-draft-release/docs/releases.md)  ✨✨✨
> no more manual drafting of release notes

- script/package.sh
- script/update-test-harness.js
- test/macos.sh
- test/ubuntu.sh
- test/win32.sh
When you pipe a string to a file on disk it adds a `\n`, which was added in #111. I worked around this when reading the checksum file by trimming whitespace, but this PR now negates that workaround and ensures the file contents (64 bytes) is just the checksum.
This also updates the test scripts after bumping Git LFS in #112
> strip newline from checksum files when writing to disk

- docker/arm64/Dockerfile
- script/build-arm64-git.sh
- script/build-arm64.sh
This shaves ~3mins from the ARM64 build (24mins -> 21mins) - not a huge win, but a win nonetheless.
> introduce docker image to speed up ARM64 builds

- script/package.sh
We follow Git's numeric versioning here (e.g. `2.19.1`) and add an extra number to the Git tag (e.g. `2.19.1-2`) to indicate further updates, but we don't use the tag in the file name. I want to avoid our tagged version being interpreted as Git's version, but this has lead to some confusion with file caching (`dugite` handles it fine, but end users see some "cached version invalid" messages that actually meant it was looking at the old version).
This PR embeds the abbreviated commit ID of `dugite-native` into the filename to help with traceability and cache-busting.
> add source SHA to build artifacts

- script/build-arm64.sh
- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
I tried to move the warnings at the end of each `build-*.sh` to a separate shared script, but couldn't make it work due to the relative paths used. I also tried to move that logic to the end of `build.sh` but that part doesn't get executed for some reason. Help welcome there.
> Get LFS only when GIT_LFS_VERSION is set and warn if not

- script/build-arm64.sh
- script/build-ubuntu.sh
Before I look to address #109 (by building `curl` myself? by statically linking?) I'd like to confirm the mismatch between `libcurl.so.4` and `CURL_OPENSSL_3` that I've painted myself into.
> adding verification about curl linking details

- script/build-ubuntu.sh
Not sure how I ended up like this, but environment variables _after_ the `make` command are probably not being applied. This PR tries to get these in the right order.
> linux: apply the flags in the right spots

- script/build-arm64.sh
- script/build-ubuntu.sh
I overlooked this in #123 but this step should look at the output directory for the downloaded certificate bundle
> linux/arm: look at the destination for the downloaded bundle

- docker/arm64/Dockerfile
- script/build-arm64-git.sh
> linux/arm64: reorder git build steps to ensure environment variables are set

- .travis.yml
- docker/arm64/Dockerfile
- script/build-arm64-git.sh
- script/build-arm64.sh
- script/build-ubuntu.sh
- script/build.sh
- script/verify-arm64-git.sh
A first pass at resolving #109 by linking to `CURL_OPENSSL_4` and `libcurl.so.4` rather than our current situation of `CURL_OPENSSL_3` and `libcurl.so.4`.
- Linux build
- ARM64 build
> linux/arm64: build a vanilla libcurl and link to that

- .travis.yml
- script/build-arm64-git.sh
- script/build-arm64.sh
- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
- script/build.sh
- script/check-static-linking.sh
- script/compute-checksum.sh
- script/package.sh
- script/update-test-harness.js
- script/verify-arm64-git.sh
> add shellcheck verification to keep scripts under control

- script/build-arm64-git.sh
- script/build-arm64.sh
- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
- script/build.sh
- script/check-static-linking.sh
- script/compute-checksum.sh
- script/package.sh
- script/verify-arm64-git.sh
Rather than mixing up script arguments (the old way I was passing things in) and environment variables (the easier way to pass things when running inside Docker) this PR tries to standardize on using environment variables. We were pretty consistent with names inside the scripts, so this should not be a big deal.
This PR also adds runtime checks to ensure the environment variables, so we can fail the scripts fast if the preconditions aren't set.
> push more parameters into environment variables

- appveyor.yml
- script/package.sh
- script/update-test-harness.js
- test/macos.sh
- test/ubuntu.sh
- test/win32.sh
Appveyor currently quietly fails when running `script/package.sh` because the version of `tar` it has there cannot access `lzma`. Here's an example build: https://ci.appveyor.com/project/github-windows/dugite-native/builds/20038933
```
Creating archives...
/bin/sh: lzma: command not found
tar: dugite-native-v2.19.1-cef2e3b-windows-x64.lzma: Cannot write: Broken pipe
tar: Child returned status 127
tar: Error is not recoverable: exiting now
Packages created:
dugite-native-v2.19.1-cef2e3b-windows-x64.tar.gz - 24M - checksum: 2505622addfa0b32dedf7e6b5dfd900f84a143c1e15fae423d2ff1422405680b
dugite-native-v2.19.1-cef2e3b-windows-x64.lzma - 0 - checksum: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
This PR changes the support for running scripts under a Windows host:
> make the publish step Windows-aware

- .travis.yml
- appveyor.yml
- dependencies.json
- package-lock.json
- package.json
- script/generate-appveyor-config.js
- script/generate-travis-config.js
- script/update-test-harness.js
This PR introduces a canonical `dependencies.json` file that defines everything needed for generating a `dugite-native` package.
The goal here is to have a consistent source of truth for things like files and checksums to simplify two things:
- when upgrading dependencies, have one place to upgrade them (instead of multiple locations with their own quirks)
- we can derive all the artifacts we need from this source, using a repeatable script rather than manual processes
As part of investigating #140 I found myself wanting to read the YAML config files to use them as a source of truth, but this felt flaky because we have two configs and they often get out of sync because we forget to update one (potentially two if I keep pushing #122 along and use Azure Pipelines).
With this approach, we …
> use dependencies to generate build config

- docs/adding-new-components.md
- docs/making-changes.md
- docs/releases.md
- docs/updating-dependencies.md
This PR updates the documentation about updating dependencies, because now it's significantly more automated.
**Rendered markdown**:
- [Making Changes](https://github.com/desktop/dugite-native/blob/writing-some-docs/docs/making-changes.md) - updating dependencies is now a scripted process, so this document is now vastly simplified
- [Updating Dependencies](https://github.com/desktop/dugite-native/blob/writing-some-docs/docs/updating-dependencies.md) - this explains the new scripts for updating Git and Git LFS 
- [Adding New Components](https://github.com/desktop/dugite-native/blob/writing-some-docs/docs/adding-new-components.md) - to ensure we can support other new components, we need a consistent way to update and package these
> refreshing the docs

- .travis.yml
- package-lock.json
- package.json
- script/generate-appveyor-config.js
- script/generate-release-notes.js
- script/generate-travis-config.js
- script/update-git-lfs.js
- script/update-git.js
- script/update-test-harness.js
- tsconfig.json
This PR adds support for type-checking the current JS files without rewriting them to `.ts` files. [This wiki page](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files) is a good walkthrough of the hooks available.
This adds an additional step to the build matrix to `npm run check`, which uses a simple `tsconfig.json` to process all the `script/*.js` files. I'll annotate the rest of the PR with the other changes as that's easier to explain there.
> do some type checking of the current set of scripts

- .travis.yml
- script/generate-travis-config.js
I spotted that #152 introduced an error, but it didn't report the error until all the agents had completed.
I want faster feedback than that, and I think this is the right config flag based on [this post](https://blog.travis-ci.com/2013-11-27-fast-finishing-builds).
> fail the travis build if any step triggers an error

- package-lock.json
- package.json
- script/generate-release-notes.js
- script/update-git-lfs.js
- script/update-git.js
It turns out that #152 is a major version jump, and [`v16.0.1`](https://github.com/octokit/rest.js/releases/tag/v16.0.1) has some important instructions to help migrate:
> To upgrade to v16, make sure you have the latest v15 release installed first:
>
> ```
> npm install @octokit/rest@15.18.0
> ```
>
> Now run the tests and look for `DEPRECATED` messages in the logs. Once you see no more deprecations, upgrading to v16 should cause no problems.
This PR moves us up to that version and addresses the issues reported by `npm run check`, which should then make Dependabot's life easier.
> interim dependency upgrade for octokit

- .travis.yml
- script/generate-travis-config.js
I believe the matrix of build configs is prioritized from top-to-bottom (based on agent availability), so this PR prioritizes `shellcheck` and `npm run check` (both running on Linux agents) before any of the packaging build configs.
This will help with #156 to verify build scripts before they are run.
> run shellcheck and js check steps before packaging

- .travis.yml
- appveyor.yml
- dependencies.json
- script/build-arm64-git.sh
- script/build-arm64.sh
I was originally planning to go to `v2.20.0` but it looks like `v2.20.1` dropped yesterday to address a couple of reported breakages:
- [Git v2.20.0 release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.20.0.txt)
- [Git v2.20.1 release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.20.1.txt)
- [Git for Windows v2.20.0 release notes](https://github.com/git-for-windows/git/releases/tag/v2.20.0.windows.1)
- [Git for Windows v2.20.1 release notes](https://github.com/git-for-windows/git/releases/tag/v2.20.1.windows.1)
TODO:
```
/home/travis/build/desktop/dugite-native/script/build-arm64-git.sh: 5: /home/travis/build/desktop/dugite-native/script/build-arm64-git.sh: [[: not found
/home/travis/build/desktop/dugite-native/script/build-arm64-git.sh: …
```
> Update Git to v2.20.1

- dependencies.json
- script/update-git-lfs.js
- script/update-git.js
This PR tidies up our `update-git` and `update-git-lfs` issues to address some corner cases in advance of #193:
- `octokit/rest` has removed the `.authenticate()` function (with a runtime error) in favour of using the `auth` constructor
- ensuring the `git` submodule exists before trying to fetch the latest tags
- the Git LFS checksums file has been tweaked slightly between updates
> refreshing setup scripts to address upstream changes

- .travis.yml
- appveyor.yml
I overlooked doing this in #259 to ensure we're building with the new `git-lfs` release
> regenerate config to consume new git-lfs update

- script/build-win32.sh
When shipping #310 we realized to late that the system gitconfig and gitattributes files in MinGit had been moved from `/mingw64/etc/` to just `/etc` in the backported Git for Windows release causing us to not be able to apply our custom gitconfig changes.
https://ci.appveyor.com/project/github-windows/dugite-native/builds/29448631/job/4xehkkqhbfy0g09c
@dscho As per :point_up: it seems that between `2.19.2.windows.3` and `2.19.2.windows.4` the system level gitconfig has moved
```
$ unzip -l MinGit-2.19.2.windows.3-64-bit.zip |grep -E 'git(config|attributes)'
329  08-17-2019 20:54   mingw64/etc/gitattributes
406  08-17-2019 20:54   mingw64/etc/gitconfig
$ unzip -l MinGit-2.19.2.windows.4-64-bit.zip |grep -E 'git(config|attributes)'
329  11-23-2019 23:10   etc/gitattributes
558  11-23-2019 …
```
> Strip system gitattributes file and update system git config file location

- script/build-win32.sh
After an enlightening discussion with @dscho I've decided that we'll pull the `include` section from the system level git config that ships in dugite for now.
In versions of Git for Windows prior to 2.24.0 the Git config hierarchy looked something like this (h/t @dscho)
```
c:\ProgramData\Git\config < our system config < xdg_config < global < repo < command-line
```
In versions post 2.24.0 the hierarchy will instead look like this
```
c:\Program Files (x86)\Git\config < c:\Program Files\Git\config < our system config < xdg_config < global < repo < command-line
```
The `ProgramData` config was hard coded into Git for Windows but that's changes for the ProgramFiles location in 2.24.0 to be an include section in the system level config.
For 2.24.0 releases of Dugite we should most likely …
> Skip including gitconfig file from Program Files

- .travis.yml
- appveyor.yml
- dependencies.json
- script/generate-release-notes.ts
Closes #303
[Git for Windows 2.23.0.windows.2](https://github.com/git-for-windows/git/releases/tag/v2.23.0.windows.2) and [Git 2.23.1](https://github.com/git/git/releases/tag/v2.23.1)
Punt until next upgrade
> Bump to Git 2.23.1

- package.json
These are no longer necessary now that we're using GitHub Actions
> Get rid of obsolete scripts

- .github/workflows/ci.yml
Our last release seemed to cause issues in dugite
```
/home/runner/work/dugite/dugite/git/bin/git: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/runner/work/dugite/dugite/git/bin/git)
```
So we're trying a simple downgrade of the runner as our first attempt
> Release 2.26.2-3

- script/build-macos.sh
On the GitHub Actions macOS runners the curl-config command resolves to a homebrew-installed version of curl which ends up providing us with a library search path (-L/usr/local/Cellar/curl/7.74.0/lib) instead of simply `-lcurl`. This causes problems when the git binaries are used on systems that don't have the homebrew version of curl. We want to use the system-provided curl.
Specifically we saw this be a problem when the git-remote-https binary was signed during the bundling process of GitHub Desktop and attempts to execute it would trigger the following error
```
dyld: Library not loaded: /usr/local/opt/curl/lib/libcurl.4.dylib
Referenced from: /Applications/GitHub Desktop.app/[...]/git-remote-https
Reason: image not found
```
> Use system curl-config to avoid issues with homebrew curl

- .github/workflows/ci.yml
I think building it with the latest Xcode version might cause some issues in older macOS. See desktop/desktop#11516
> Change CI to use an older Xcode to build git for macOS

- .github/workflows/ci.yml
- dependencies.json
- script/build-macos.sh
- script/generate-release-notes.ts
- script/package.sh
This PR fixes the build-macos script and our CI workflow to allow generating macOS builds of git and git-lfs for arm64.
In order to do that there are a couple of "hacks":
- Use `DEVELOPER_CLFAGS` to "inject" our `-target` cflag to specify the target architecture.
- Fix git-lfs Makefile to prevent it from failing when cross-compiling. See https://github.com/git-lfs/git-lfs/pull/4492 for more details.
> Generate arm64 builds of git and git-lfs

- .github/workflows/ci.yml
- dependencies.json
This PR bumps…
- Git to 2.32.0
- Git LFS to 2.13.3
> Bump Git to 2.32.0 and Git LFS to 2.13.3

- dependencies.json
Upgrades Git to 2.35.2 (latest stable release)
> Bump Git to 2.35.2

- dependencies.json
- script/build-ubuntu.sh
Bumps git to 2.39.1, git for windows to v2.39.1.windows.1 and git-lfs to 3.3.0.
> Bump git to 2.39.1 and git-lfs to 3.3.0

- dependencies.json
Bumps Git to 2.39.2 and Git for Windows to v2.39.2.windows.1
> Bump to 2.39.2

- .github/workflows/ci.yml
- dependencies.json
- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
- script/check-static-linking.sh
- script/package.sh
- script/update-git-lfs.ts
Uses cross compilation to build and publish ARM32 and ARM64 linux builds. Successful action run here: https://github.com/theofficialgman/dugite-native/actions/runs/4213237492
The builds are very fast 🔥, equal to the speed of x64 linux or faster sometimes.
Spiritual successor to https://github.com/desktop/dugite-native/pull/330 
Fixes https://github.com/desktop/dugite-native/pull/315
Replacement for https://github.com/desktop/dugite-native/pull/368
Closes https://github.com/desktop/dugite-native/issues/158
Closes https://github.com/desktop/dugite/issues/521
progress for https://github.com/shiftkey/desktop/issues/251
in tandum with https://github.com/desktop/dugite/pull/522
Necessary for @shiftkey linux github desktop ARM and ARM64 builds in CI 
LGTM!
> Add ARM64, ARM32, and x86 Linux Builds

- .github/workflows/ci.yml
- dependencies.json
- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
- script/check-static-linking.sh
- script/package.sh
- script/update-git-lfs.ts
Bumps Git to 2.39.3 and Git for Windows to v2.39.3.windows.1
EDIT: 
- Linux builds were not being picked up by action.
- Found that on April 3rd, [actions no longer supports ubuntu-18.04](https://github.com/actions/runner-images/issues/6002)
- Tried `ubuntu-latest` which should be `ubuntu-22.04` and `ubuntu-20.04` and they both failed.
- Reverted [#414 - Add ARM64, ARM32, and x86 Linux Builds](https://github.com/desktop/dugite-native/pull/414) and updated to `ubuntu-22.04` and build succeeds. We will have to revisit Arm64 builds for linux.
> Bump to 2.39.3

- .github/workflows/ci.yml
- README.md
- dependencies.json
- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
- script/check-static-linking.sh
- script/package.sh
- script/update-git-lfs.ts
this PR also relands my previous x86, arm, and arm64 PR with no necessary changes to build other than bumping the version
> Ubuntu switch to 20.04 and add patches to minimize GLIBC requirements

- .github/workflows/ci.yml
It seems [macos-10.15 runners were deprecated & removed months ago](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22) (still don’t understand how it worked since then) and on Friday whatever was left got finally removed.
This PR bumps dugite’s runners to a more recent macOS version. I’m mainly concerned about the fact that [we relied on an older Xcode version to maximize compatibility with older macOS versions](https://github.com/desktop/dugite-native/blob/7082cf8c53e544fd74824881d9c61bb580f972c2/.github/workflows/ci.yml#L59-L66) and that won’t be possible now (at least not with the same version, AFAIK).
> Bump macOS CI runners

- .github/workflows/ci.yml
- script/generate-release-notes.ts
This addresses a CI failure I found when pushing a tag to my fork:
https://github.com/shiftkey/dugite-native/actions/runs/5446431880/jobs/9907349797#step:6:36
```
🔴 Artifacts folder has 32 assets, expecting 20. Please check the GH Actions artifacts to see which are missing.
```
This is because we have new platforms included, but the count is out of sync. 
The second commit resolves a linter warning where you need to check for `NaN` in the right way:
The third commit is a `permissions` addition because actions on forks [do not have permissions to write `content` by default when in restricted mode](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).
Working release links:
- …
> Fixes for release notes script

- dependencies.json
This PR upgrades:
- Git to v2.43.3
- Git for Windows to v2.43.0.windows.1 (as there is no v2.43.3 version)
- Git LFS to v3.5.1
> Bump git to v2.43.x and git lfs to v3.5.1

- .github/workflows/ci.yml
- resources/posix.gitconfig
- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
Git for Windows ships a whole environment including its own /etc/gitconfig which we can (and do) manipulate during build in order to insert our "sane defaults" into it. On macOS and Linux that's not the case so in this PR we're creating our own system level config that dugite can then instruct Git to use.
> Add a custom "system level" gitconfig

- .github/workflows/ci.yml
- Upgrade `upload-artifacts` and `download-artifacts` to v4
- In order to do that, bump the GLIBC requirements by using Ubuntu 20.04 to build Dugite
- I noticed `macos-11` runners are not available anymore, so I bumped those to `macos-12` and we will use Xcode 13.1 from now on (it's the oldest one available, for maximum compatibility).
> Bump artifact-related actions to v4

- .github/workflows/ci.yml
As of https://github.com/desktop/dugite-native/commit/4981d67487f4ccbedcd1301d3a682e7f76160faf we're bundling the precompiled Git LFS binaries on macOS so we don't need go any more.
> Don't need go any more

- script/build-macos.sh
- script/build-ubuntu.sh
- script/build-win32.sh
- script/verify-lfs-contents.sh
We found out that we were shipping the man pages for LFS into the libexec folder. No need for that, let's just get rid of everything that's not the LFS executable.
> Only package the bits from LFS that we really need

- .github/workflows/ci.yml
- dependencies.json
- script/build-win32.sh
- script/update-git-lfs.ts
- script/update-git.ts
Git for Windows added support for arm64 releases in their 2.47.1 version. Let's add support for it in the `update-git.ts` script.
I also ran the `update-git.ts` script after adding this change, which correctly added the arm64 version of Git to `dependencies.json`. I'll leave it up to you if you also want to include that commit already, or if you want to address the version bump separately.
Ref: https://github.com/git-for-windows/git/releases/tag/v2.47.1.windows.1
Ref: https://github.com/git-for-windows/git/issues/3107#issuecomment-2498275856
> Add arm64 support for Git for Windows and update to 2.47.1

- .github/workflows/ci.yml
- dependencies.json
- script/build-ubuntu.sh
2.49.0 is the latest version of Git but I spoke with `@dscho` and it seems there are no bugs of concern so let's go for it.
> Bump Git to 2.49.0
