.travis.yml
=> bump to Git 2.13.0

.gitignore, script/build-win32.sh
=> cleanup curl workaround and set http.sslBackend on system config

.travis.yml, appveyor.yml, test/macos.sh, test/ubuntu.sh, test/win32.sh
=> Update to LFS 2.3.0

.travis.yml, package-lock.json, package.json, test/macos.sh, test/ubuntu.sh, test/win32.sh
- Git 2.14.2 [release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.14.2.txt)
- Git for Windows 2.14.2 [release notes](https://github.com/git-for-windows/git/releases/tag/v2.14.2.windows.1)
- Git LFS 2.3.1 [release notes](https://github.com/git-lfs/git-lfs/releases/tag/v2.3.1)
=> Update Git to 2.14.2 and Git LFS to 2.3.1

.travis.yml, appveyor.yml
- [Git Release Notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.14.3.txt)
- [Git for Windows Release Notes](https://github.com/git-for-windows/git/releases/tag/v2.14.3.windows.1)
=> update Git to 2.14.3

.travis.yml, test/win32.sh
- [Git release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.15.1.txt)
- [Git for Windows release notes](https://github.com/git-for-windows/git/releases/tag/v2.15.1.windows.1)
=> update to Git 2.15.1

script/build-macos.sh, script/build-ubuntu.sh
=> tidy up some unsupported Git features

script/build-ubuntu.sh
Playing around with [Ermine](http://www.magicermine.com) locally, and these changes help to identify what needed to be statically linked, as well as the difference in the resulting archive...
=> digging into static linking of Git

script/build-ubuntu.sh, script/package.sh
And some other assorted cleanup
=> cleanup static lookup

.travis.yml, appveyor.yml, test/win32.sh
This is of interest to GitHub Desktop because of https://github.com/desktop/desktop/issues/3618, so let's see if we can put together a pre-release package of it.
=> Git 2.16.0-rc0

script/build-win32.sh
=> set some common default values on Windows

.travis.yml, appveyor.yml, script/build-win32.sh, script/package.sh
=> Add Windows 32-bit support

script/build-arm64.sh
A better shot at #113 - credit to @ttaylorr for identifying the issue I faced previously
=> switch ARM64 agent over to use new build steps

script/build-ubuntu.sh
Related downstream issue: https://github.com/desktop/dugite/issues/222
=> emit build details about glibc linking

script/generate-release-notes.js
=> release notes improvements

.travis.yml, script/build-arm64.sh, script/build-win32.sh
- [Release notes](https://github.com/git-lfs/git-lfs/releases/tag/v2.6.0)
=> update git-lfs to 2.6.0

dependencies.json, package-lock.json, package.json, script/update-git.js
=> add script for updating Git dependencies to latest version

.travis.yml, appveyor.yml, dependencies.json
=> Update Git to 2.19.2

.travis.yml, appveyor.yml, dependencies.json
Nothing ground-breaking, but a couple of good bugfixes to pull in.
- [Release notes](https://github.com/git-lfs/git-lfs/releases/tag/v2.6.1)
=> update git-lfs to 2.6.1

docs/updating-dependencies.md
I overlooked this section in #147 because the steps to do this are now much easier to perform (yay automation!)
=> refresh sections about updating Git

.travis.yml, appveyor.yml, dependencies.json
=> Git 2.21.0

dependencies.json
=> update git-lfs dependencies

script/generate-release-notes.js
=> remove deprecated octokit API

package-lock.json, package.json, script/generate-appveyor-config.ts, script/generate-release-notes.ts, script/generate-travis-config.ts, script/update-git-lfs.ts, script/update-git.ts, script/update-test-harness.ts, tsconfig.json
**Closes #149**
- Ported the JS scripts over to TS and migrated the `@type` comments to proper type annotations
=> port JS scripts to TS

script/generate-appveyor-config.ts, script/generate-travis-config.ts, script/lib/dependencies.ts, script/update-git-lfs.ts, script/update-git.ts, tsconfig.json
=> leverage the type checker and make things better organized

script/build-win32.sh
Backports #313 on top of #312. Will be released as 2.19.3-2
=> Release 2.19.3-2

.travis.yml, appveyor.yml, dependencies.json
Mitigates https://github.com/desktop/desktop/issues/9597
=> Upgrade to MinGit 2.23.0.windows.5

.travis.yml, appveyor.yml, dependencies.json
=> git 2.26.2

.github/workflows/ci.yml, dependencies.json, script/update-git-lfs.ts
Update Git LFS to 2.13.2 to fix CVE-2021-21237.
=> Release Git-2.26.2-2 with Git LFS 2.13.2

dependencies.json
Bump to git 2.29.3 and g4w to 2.29.2.windows.4
=> Bump to git 2.29.3 and g4w to 2.29.2.windows.4

dependencies.json
Bump to git 2.32.1 and g4w to 2.32.1.windows.1
=> Bump to git 2.32.1 and g4w to 2.32.1.windows.1

dependencies.json, package-lock.json
Bumps git to 2.35.5 and git for windows to v2.35.5.windows.1
=> Release v2.35.5

dependencies.json
Bumps git to 2.35.6 and git for windows to v2.35.6.windows.1
=> Bump to 2.35.6

.github/workflows/ci.yml, script/build-ubuntu.sh
Align better with how Ubuntu packages their git package
=> Change build dependencies

.github/workflows/ci.yml, dependencies.json, script/build-macos.sh, script/update-git-lfs.ts
=> Bump Git things.. 

script/generate-release-notes.ts
Update number of expected artifacts to account for Windows for arm64 binaries.
Related: https://github.com/desktop/dugite-native/actions/runs/12889948117/job/35938799776#step:5:62
=> Update number of expected artifacts

.github/workflows/ci.yml, dependencies.json
This updates to:
Git to 2.47.3
Git For Windows v2.47.3.windows.1
=> Release v2.47.3
